name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t myfirstapp:v1 .
    - name: Tagging Docker Image
      run: docker tag myfirstapp ssgpdocker/myfirstapp 
    - name: Deply docker image
      run: docker push ssgpdocker/myfirstapp 
